### ISSUE TITLE
Clients are not notified on Connection Destroyed event

### ISSUE THREAD

**Issue by Stopka** [OpenVidu/openvidu#58]
I am trying to upgrade openvidu to newset 2.0.0 (docker _openvidu/openvidu-server:2.0.0_ with separate _docker kurento/kurento-media-server:6.7.1-xenial_) and have problem that connected clients are not notified when one of them disconnects. This causes frozen thumbnail window hanging in the gui. This used to work at least on openvidu-server:1.1.0.

**Comment by pabloFuente** [comment]
You mean that no events `streamDestroyed` and `connectionDestroyed` are dispatched by Session object?

**Comment by Stopka** [comment]
Yes.

**Comment by pabloFuente** [comment]
Please, can you show your client side code where you configure your Session object? These events are being properly triggered in all our tutorials and tests for last release 2.0.0. There's really no way for our release process to successfully finish without these events.

Take into account that OpenVidu 2.0.0 brings some breaking changes with respect to previous 1.X.X that may be interfering in your existing code. You have all of them listed [here](https://openvidu.io/docs/releases/#breaking-changes-list).

Regards

**Comment by pabloFuente** [comment]
This was fixed in version 2.0.0

Please, try the following steps:

Connect to the same session on https://demos.openvidu.io/getaroom/ in two different devices. Then disconnect one of them from its network connection.

After like 10 seconds, you will see in the other device that the layout is updated as if the other user left the session. If you open the browser's console in the remaining user, you can see the following event:

![selection_191](https://user-images.githubusercontent.com/15049534/40371121-1ca89706-5de2-11e8-953c-dfcbff6ec392.png)

Notice the "reason" property saying "networkDisconnect". In this case local Session objects are only subscribed to `streamDestroyed` event, but if `connectionDestroyed` event was also set in the object, it will also be dispatched just after the `streamDestroyed` event, also with "reason: networkDisconnect".

I have tested this right now, and OpenVidu Demos are running with OpenVidu 2.0.0. Feel free to test this same scenario on your own.

**Comment by Stopka** [comment]
I can't figure it out. The most simple example is this:

```
var OV = new OpenVidu();
var session = OV.initSession();
var token = loadToken();
session.connect(token)
    .then(function(){
        
    })
    .catch(function(){

    });
```

As I understand, after this code we have running connection to openvidu and I can catch frames of websocket connection or just watch debug info in console to see retrieved events. And even in this simple example it does not recieve participantLeft aka connectionDestroyed event from the server.

I can provide some logs:

# After A connects
A's browser console:
```
OpenVidu.ts:65 'OpenVidu' initialized
Connection.ts:74 'Connection' created (local)
Connection.ts:74 'Connection' created (remote) with 'connectionId' [3bblbzp4gxyhqlj9]
```
server log:
```
2018-06-05 20:42:42,369 DEBG 'openvidu-server' stdout output:
[INFO] 2018-06-05 20:42:42,368 [-8444-exec-8] io.openvidu.server.core.SessionManager (showTokens) - <SESSIONID, TOKENS>: {qeoixbor0ereky4l={}}

2018-06-05 20:42:42,514 DEBG 'openvidu-server' stdout output:
[INFO] 2018-06-05 20:42:42,513 [-8444-exec-3] io.openvidu.server.core.SessionManager (showTokens) - <SESSIONID, TOKENS>: {qeoixbor0ereky4l={wss://(...)}}

2018-06-05 20:42:44,703 DEBG 'openvidu-server' stdout output:
[INFO] 2018-06-05 20:42:44,702 [8444-exec-10] io.openvidu.server.rpc.RpcHandler (afterConnectionEstablished) - After connection established for WebSocket session: 7a4pjmtlv7bimnq42l8i3qg82s

2018-06-05 20:42:44,777 DEBG 'openvidu-server' stdout output:
[WARN] 2018-06-05 20:42:44,776 [3qg82s-e2-t0] io.openvidu.server.kurento.core.KurentoSessionManager (createSession) - No session 'qeoixbor0ereky4l' exists yet. Created one using KurentoClient 'manager_ServerManager'.

2018-06-05 20:42:44,781 DEBG 'openvidu-server' stdout output:
[INFO] 2018-06-05 20:42:44,779 [3qg82s-e2-t0] io.openvidu.server.core.Session (createPipeline) - SESSION qeoixbor0ereky4l: Creating MediaPipeline

2018-06-05 20:42:44,896 DEBG 'openvidu-server' stdout output:
[INFO] 2018-06-05 20:42:44,895 [3qg82s-e2-t0] io.openvidu.server.core.Session (join) - SESSION qeoixbor0ereky4l: Added participant [participantPrivateId=7a4pjmtlv7bimnq42l8i3qg82s, participantPublicId=jxdcu22to0mf3y9k, streaming=false]

2018-06-05 20:42:44,902 DEBG 'openvidu-server' stdout output:
[INFO] 2018-06-05 20:42:44,897 [3qg82s-e2-t0] io.openvidu.server.cdr.CallDetailRecord (recordParticipantJoined) - {"participantJoined":{"participantId":"jxdcu22to0mf3y9k","sessionId":"qeoixbor0ereky4l","timestamp":1528231364897}}
```


# B connects
A's browser console:

```
Connection.ts:74 'Connection' created (remote) with 'connectionId' [3bblbzp4gxyhqlj9]
```
server:
```
2018-06-05 20:44:48,018 DEBG 'openvidu-server' stdout output:
[INFO] 2018-06-05 20:44:48,017 [8444-exec-10] io.openvidu.server.core.SessionManager (showTokens) - <SESSIONID, TOKENS>: {qeoixbor0ereky4l={wss://(...)}}

2018-06-05 20:44:50,529 DEBG 'openvidu-server' stdout output:
[INFO] 2018-06-05 20:44:50,529 [-8444-exec-9] io.openvidu.server.rpc.RpcHandler (afterConnectionEstablished) - After connection established for WebSocket session: ll0ko0o21qvtruli34vaqh749f

2018-06-05 20:44:50,535 DEBG 'openvidu-server' stdout output:
[INFO] 2018-06-05 20:44:50,535 [qh749f-e5-t0] io.openvidu.server.core.Session (join) - SESSION qeoixbor0ereky4l: Added participant [participantPrivateId=ll0ko0o21qvtruli34vaqh749f, participantPublicId=3bblbzp4gxyhqlj9, streaming=false]

2018-06-05 20:44:50,536 DEBG 'openvidu-server' stdout output:
[INFO] 2018-06-05 20:44:50,536 [qh749f-e5-t0] io.openvidu.server.cdr.CallDetailRecord (recordParticipantJoined) - {"participantJoined":{"participantId":"3bblbzp4gxyhqlj9","sessionId":"qeoixbor0ereky4l","timestamp":1528231490536}}
```


# B disconnects by leaving page, without calling session.leave
A's browser console: _nothing_

server:
```
2018-06-05 20:46:27,441 DEBG 'openvidu-server' stdout output:
[INFO] 2018-06-05 20:46:27,440 [kScheduler-1] io.openvidu.server.rpc.RpcHandler (afterConnectionClosed) - After connection closed for WebSocket session: ll0ko0o21qvtruli34vaqh749f - Status: null
```

# B connects again
A's browser console:
```
Connection.ts:74 'Connection' created (remote) with 'connectionId' [5cdrvge3dlim71eb]
```
Server:
```
2018-06-05 20:47:21,426 DEBG 'openvidu-server' stdout output:
[INFO] 2018-06-05 20:47:21,426 [8444-exec-10] io.openvidu.server.core.SessionManager (showTokens) - <SESSIONID, TOKENS>: {qeoixbor0ereky4l={wss://(...)}}

2018-06-05 20:47:24,028 DEBG 'openvidu-server' stdout output:
[INFO] 2018-06-05 20:47:24,027 [-8444-exec-8] io.openvidu.server.rpc.RpcHandler (afterConnectionEstablished) - After connection established for WebSocket session: fon49ovsur2ju43uatcmrvhr5r

2018-06-05 20:47:24,029 DEBG 'openvidu-server' stdout output:
[INFO] 2018-06-05 20:47:24,029 [rvhr5r-e6-t0] io.openvidu.server.core.Session (join) - SESSION qeoixbor0ereky4l: Added participant [participantPrivateId=fon49ovsur2ju43uatcmrvhr5r, participantPublicId=5cdrvge3dlim71eb, streaming=false]

2018-06-05 20:47:24,029 DEBG 'openvidu-server' stdout output:
[INFO] 2018-06-05 20:47:24,029 [rvhr5r-e6-t0] io.openvidu.server.cdr.CallDetailRecord (recordParticipantJoined) - {"participantJoined":{"participantId":"5cdrvge3dlim71eb","sessionId":"qeoixbor0ereky4l","timestamp":1528231644029}}

2018-06-05 20:47:24,035 DEBG 'openvidu-server' stdout output:
[ERROR] 2018-06-05 20:47:24,034 [rvhr5r-e6-t0] io.openvidu.server.rpc.RpcNotificationService (sendNotification) - Exception sending notification 'participantJoined': {"id":"5cdrvge3dlim71eb","metadata":"{\"username\":\"admin\",\"name\":\"John\",\"surname\":\"Smith\",\"role\":\"student\"}"} to participant with private id ll0ko0o21qvtruli34vaqh749f
org.kurento.commons.exception.KurentoException: Exception while sending message '{"method":"participantJoined","params":{"id":"5cdrvge3dlim71eb","metadata":"{\"username\":\"admin\",\"name\":\"John\",\"surname\":\"Smith\",\"role\":\"student\"}"},"jsonrpc":"2.0"}' to websocket with native sessionId '1'
	at org.kurento.jsonrpc.internal.ws.WebSocketServerSession.sendRequestWebSocket(WebSocketServerSession.java:120)
	at org.kurento.jsonrpc.internal.ws.WebSocketServerSession.access$000(WebSocketServerSession.java:48)
	at org.kurento.jsonrpc.internal.ws.WebSocketServerSession$1.internalSendRequest(WebSocketServerSession.java:72)
	at org.kurento.jsonrpc.internal.JsonRpcRequestSenderHelper.sendRequest(JsonRpcRequestSenderHelper.java:75)
	at org.kurento.jsonrpc.internal.JsonRpcRequestSenderHelper.sendNotification(JsonRpcRequestSenderHelper.java:156)
	at org.kurento.jsonrpc.internal.server.ServerSession.sendNotification(ServerSession.java:121)
	at io.openvidu.server.rpc.RpcNotificationService.sendNotification(RpcNotificationService.java:98)
	at io.openvidu.server.core.SessionEventsHandler.onParticipantJoined(SessionEventsHandler.java:142)
	at io.openvidu.server.kurento.core.KurentoSessionManager.joinRoom(KurentoSessionManager.java:102)
	at io.openvidu.server.rpc.RpcHandler.joinRoom(RpcHandler.java:173)
	at io.openvidu.server.rpc.RpcHandler.handleRequest(RpcHandler.java:101)
	at org.kurento.jsonrpc.internal.JsonRpcHandlerManager.handleRequest(JsonRpcHandlerManager.java:128)
	at org.kurento.jsonrpc.internal.server.ProtocolManager$3.run(ProtocolManager.java:218)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: The WebSocket session [1] has been closed and no method (apart from close()) may be called on a closed session
	at org.apache.tomcat.websocket.WsSession.checkState(WsSession.java:803)
	at org.apache.tomcat.websocket.WsSession.getBasicRemote(WsSession.java:446)
	at org.springframework.web.socket.adapter.standard.StandardWebSocketSession.sendTextMessage(StandardWebSocketSession.java:197)
	at org.springframework.web.socket.adapter.AbstractWebSocketSession.sendMessage(AbstractWebSocketSession.java:104)
	at org.kurento.jsonrpc.internal.ws.WebSocketServerSession.sendRequestWebSocket(WebSocketServerSession.java:117)
	... 15 common frames omitted
```

Tested on docker openvidu/openvuidu-server:2.1.0 + openvidu-browser:2.1.0

**Comment by pabloFuente** [comment]
This behavior should be fixed by now. OpenVidu Server 2.2.0 includes some new changes into cleint's websocket lifecycle management.

**Comment by Stopka** [comment]
Thanks, will try it next week

**Comment by robin3317** [comment]
This isn't fixed, connectionDestroyed / sessionDisconnected event doesn't trigger if network problem.
