### ISSUE TITLE
Angular Components custom-layout not working properly

### ISSUE THREAD

**Issue by VaporMontey** [OpenVidu/openvidu#746]
**Describe the bug**
When using the _ParticipantService_ needed with _*ovLayout_ directive the _remoteParticipantObs_ won't receive any event

**Expected behavior**
When subscribed to _remoteParticipantObs_ and after a remote participant is connected a new array of _ParticipantAbstractModel[]_ is received

**Wrong current behavior**
No event are fired when subscribed to _remoteParticipantObs_ and a remote participant is connected

**OpenVidu tutorial where to replicate the error**
- Just run the [openvidu-custom-layout](https://docs.openvidu.io/en/2.22.0/components/openvidu-custom-layout/#run-this-tutorial)
tutorial.
- To simulate multiple users I've opened some tabs on my Chrome browser
- The remote participants populates on the _<ov-videoconference>_ component when not utilizing the  _*ovLayout_  directive
- The same behaviour happens on my server and on yours (https://demos.openvidu.io)

**OpenVidu deployment info**
Openvidu deployed on premises using the installation script

- Openvidu 2.22.0
- Kurento 6.16.0

**Client device info (if applicable)**
- Chrome 104.5.5112.102 (Official Build) (64-bit) on Windows 11.
- Angular 13 with openvidu-angular 2.22.0

**Screenshots**
/

**Additional context**
/

**Comment by CSantosM** [comment]
I think that bug have been fixed on master branch. Have you tested cloning the repo from master?

**Comment by VaporMontey** [comment]
Hello @CSantosM 

Just tried, I've updated the tutorials repo and even build the openvidu-angular npm module from master as you said but the problem persist

**Comment by CSantosM** [comment]
I've just tested the tutorial pointing to https://demos.openvidu.io and it is working perfectly. The remote participants events are being received properly.

![image](https://user-images.githubusercontent.com/10628395/188191400-61ec7c30-064d-47f3-815c-392ecb9187a1.png)

**Comment by VaporMontey** [comment]
Hello @CSantosM,

You are right, the new example seems to be working.

Best regards
